import {Car,TreePine,Cloud,ArrowDownRight} from 'lucide-react';
import {carbonKg,carbonNumber,drivingKm,treeYears,CEA_SOURCE,EPA_SOURCE} from '@/lib/carbon';
export function CarbonEquivalents({kg,annual=false,saving=false}:{kg:number;annual?:boolean;saving?:boolean}){
 return <div className="carbon-equivalents"><div><Car aria-hidden="true"/><p><strong>{carbonNumber(drivingKm(kg))} km</strong><span>{saving?'comparable driving emissions avoided':'comparable petrol-car driving emissions'}{annual?' / year':''}</span></p></div>{annual&&saving&&<div><TreePine aria-hidden="true"/><p><strong>{carbonNumber(treeYears(kg))} growing trees</strong><span>equivalent annual CO₂ uptake · 10-year growth average</span></p></div>}</div>;
}
export function CarbonSaving({kwh,factor,annual=true}:{kwh:number;factor:number;annual?:boolean}){
 const kg=carbonKg(kwh,factor);return <div className="carbon-saving"><ArrowDownRight aria-hidden="true"/><div><strong>{carbonNumber(kg)} kg CO₂ {annual?' / year':''}</strong><span>estimated grid emissions reduction</span><CarbonEquivalents kg={kg} annual={annual} saving/></div></div>;
}
export function CarbonSources(){return <details className="carbon-method"><summary>Carbon data, scope &amp; assumptions</summary><p>Electricity × emission factor = estimated generation-related CO₂. Default: 0.675 kg CO₂/kWh, India grid average including renewables, CEA v22, FY 2025–26, Table S. You can enter a documented supplier factor. This is electricity-related CO₂, not your complete household footprint; it excludes grid delivery losses, other greenhouse gases, fuel use, and product manufacturing.</p><p>Savings use the same average factor for a location-based scenario, not a verified marginal avoided-emissions calculation or carbon credit. Solar and wind have no direct fuel emissions in operation, but manufacturing and installation are not zero-carbon.</p><p>Driving uses EPA’s US average petrol passenger-vehicle benchmark (0.393 kg CO₂e/mile; 1 mile = 1.609344 km). Tree comparisons use 60 kg CO₂/tree/year, averaged over ten years of urban growth. These are approximate visual comparisons, not local vehicle measurements, planting promises, or offsets.</p><a href={CEA_SOURCE} target="_blank" rel="noopener noreferrer">CEA grid factor, v22 →</a><a href={EPA_SOURCE} target="_blank" rel="noopener noreferrer">EPA equivalency methodology →</a></details>}
export default function CarbonOverview({units,modeled,days,factor}:{units:number;modeled:number;days:number;factor:number}){
 const billed=carbonKg(units,factor);const estimated=carbonKg(modeled,factor);return <section className="carbon-overview" aria-labelledby="carbon-title"><div className="carbon-heading"><Cloud aria-hidden="true"/><div><span>YOUR ELECTRICITY FOOTPRINT</span><h3 id="carbon-title">See your impact, clearly.</h3><p>CO₂ associated with your electricity bill over {days} days.</p></div></div><div className="carbon-main"><div className="carbon-total"><strong>{carbonNumber(billed)}</strong><span>kg CO₂ / {days} days</span><small>{carbonNumber(carbonKg(units/days*365,factor))} kg CO₂ annualized at this usage</small></div><CarbonEquivalents kg={billed}/></div><div className="carbon-reconciliation"><span>Appliances modeled: <b>{carbonNumber(estimated)} kg CO₂</b></span><span>{modeled>units?'Model exceeds bill by':'Not allocated to appliances'}: <b>{carbonNumber(Math.abs(billed-estimated))} kg CO₂</b></span></div><p className="note">The bill is the overall electricity baseline; appliance estimates explain its breakdown. Do not add these two totals together.</p><CarbonSources/></section>;
}
