'use client';
import {useMemo} from 'react';
import {ArrowUpRight,TrendingDown} from 'lucide-react';
import {recommendUpgrades,solarScenario,type Usage} from '@/lib/recommendations';
import {money,products} from '@/lib/products';
import AIInsight from './ai-insight';
import {CarbonSaving} from './carbon-visuals';
import {usageKwh,carbonKg,carbonNumber} from '@/lib/carbon';

export default function Recommendations({items,rate,days,units,factor}:{items:Usage[];rate:number;days:number;units:number;factor:number}){
 const suggestions=useMemo(()=>recommendUpgrades(items,rate,days),[items,rate,days]);
 const solar=products.find(p=>p.category==='Solar')!;
 const solarResult=solarScenario(units,days,rate,solar.capacityKw!,solar.price,4,80);
 const annualUpgradeKwh=suggestions.reduce((sum,s)=>sum+s.savedKwh/days*365,0);
 const habit=items.filter(i=>i.hours>0&&['Ceiling fan','Air conditioner','Television','LED light','Computer'].includes(i.name)).sort((a,b)=>b.watts*b.quantity-a.watts*a.quantity)[0];
 return <section className="recommendations" aria-labelledby="recommendation-title"><div className="recommendation-heading"><TrendingDown aria-hidden="true"/><div><h3 id="recommendation-title">Your next efficient move</h3><p>Matched to your appliances and usage. Relevant partner catalog options take priority.</p></div></div><p className="sample-notice">Sample catalog: all products, prices, and specifications below are illustrative. Savings use your entered wattage and hours, not verified performance or live prices.</p>
 <AIInsight items={items} rate={rate} days={days}/>
 <div className="upgrade-list" aria-live="polite">{suggestions.length===0?<p className="empty-recommendations">No lower-power catalog match for this usage. Add a fan, AC, or light, or enter your current device’s wattage. Lower hours and an appropriate tariff are needed to estimate savings.</p>:suggestions.map(s=><article key={s.appliance.id} className="upgrade-card"><div><span className="recommendation-tag">Sample partner option</span><h4>{s.appliance.name} → {s.product.name}</h4><p>{s.appliance.watts} W to {s.product.watts} W, with the same {s.appliance.hours} hours/day and {s.appliance.quantity} device{s.appliance.quantity===1?'':'s'}.</p>{s.product.category==='Cooling'&&<p className="note">AC usage is highly variable. The 850 W figure is an assumed average, not a rated or certified saving. Match cooling capacity before comparing.</p>}</div><dl><div><dt>Replacement cost</dt><dd>{money(s.totalCost)}</dd></div><div><dt>Save per {days} days</dt><dd>{money(s.periodSavings)}</dd></div><div><dt>Annual savings</dt><dd>{money(s.annualSavings)}</dd></div><div><dt>Simple payback</dt><dd>{s.paybackYears===null?'N/A':`${s.paybackYears.toFixed(1)} years`}</dd></div></dl><div className="carbon-comparison"><span>Current: {carbonNumber(carbonKg(usageKwh(s.appliance.watts,s.appliance.hours,s.appliance.quantity,days),factor))} kg CO₂ / period</span><span>Alternative: {carbonNumber(carbonKg(usageKwh(s.product.watts!,s.appliance.hours,s.appliance.quantity,days),factor))} kg CO₂ / period</span><strong>Save {carbonNumber(carbonKg(s.savedKwh,factor))} kg CO₂ / {days} days</strong></div><CarbonSaving kwh={s.savedKwh/days*365} factor={factor}/><a className="action-link" href={`/shop#${s.product.id}`}>View this option <ArrowUpRight size={18}/></a></article>)}</div>
 {solarResult.used>0&&<article className="solar-suggestion"><div><span className="recommendation-tag">A renewable alternative</span><h4>{solar.name}</h4><p>At 4 peak sun hours/day, 20% system losses, and 80% self-consumption, capped by your current billed usage.</p></div><dl><div><dt>Sample installed cost</dt><dd>{money(solar.price)}</dd></div><div><dt>Annual savings</dt><dd>{money(solarResult.annualSavings)}</dd></div><div><dt>Simple payback</dt><dd>{solarResult.paybackYears===null?'N/A':`${solarResult.paybackYears.toFixed(1)} years`}</dd></div></dl><CarbonSaving kwh={solarResult.used} factor={factor}/><a className="action-link" href={`/shop#${solar.id}`}>Explore solar <ArrowUpRight size={18}/></a></article>}
 {annualUpgradeKwh>0&&<div className="carbon-plan"><h4>Your equipment upgrade scenario</h4><p>Replacing all matched devices above, with the same hours and quantity:</p><CarbonSaving kwh={annualUpgradeKwh} factor={factor}/><p className="note">This combines equipment upgrades only. Solar and habit scenarios below are separate.</p></div>}
 {habit&&<div className="carbon-habit"><h4>A saving without buying</h4><p>Switch off your {habit.name.toLowerCase()} when it is not needed. Reducing use by {Math.min(1,habit.hours)} hour/day across {habit.quantity} device{habit.quantity===1?'':'s'} would use {carbonNumber(usageKwh(habit.watts,Math.min(1,habit.hours),habit.quantity,days))} kWh less and save {money(usageKwh(habit.watts,Math.min(1,habit.hours),habit.quantity,days)*rate)} per {days} days.</p><CarbonSaving kwh={usageKwh(habit.watts,Math.min(1,habit.hours),habit.quantity,365)} factor={factor}/></div>}
 <p className="note">Each option is a separate scenario. Do not add solar and equipment savings together without recalculating the reduced load. Payback excludes maintenance, financing, degradation, and tariff changes. Wind needs a site assessment before any savings estimate.</p></section>;
}
