'use client';
import {useState} from 'react';
import {Fan,Sun,Wind,Snowflake,Lightbulb,ArrowUpRight} from 'lucide-react';
import {products,money,type ProductCategory} from '@/lib/products';
const icons={Fans:Fan,Solar:Sun,Wind:Wind,Cooling:Snowflake,Lighting:Lightbulb};
export default function ProductShop(){
 const [category,setCategory]=useState('All');
 const filtered=products.filter(p=>category==='All'||p.category===category);
 return <><div className="shop-intro"><span className="pathway-label">Enerlyze products</span><h1>Choose a better<br/>way to use energy.</h1><p>Efficient everyday appliances and renewable possibilities, connected to the savings you calculate.</p><div className="shop-availability">Buying is coming soon. Explore our upcoming range below. Product specifications and indicative prices will be confirmed when partner listings launch.</div></div><div className="shop-toolbar"><nav aria-label="Product categories">{['All','Fans','Cooling','Lighting','Solar','Wind'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</nav><span>{filtered.length} options</span></div><section className="product-grid" aria-label="Products">{filtered.map(p=>{const Icon=icons[p.category as ProductCategory];const available=Boolean(p.buyUrl&&!p.sample);return <article id={p.id} key={p.id} className="product-card"><div className={`product-art art-${p.category.toLowerCase()}`}><Icon size={88} strokeWidth={1} aria-hidden="true"/></div><div className="product-copy"><span className="recommendation-tag">{available?'Partner product':'Preview · coming soon'}</span><h2>{p.name}</h2><p>{p.description}</p><span className="product-spec">{p.spec}</span><div className="product-price"><strong>{money(p.price)}</strong><span>{p.sample?'indicative price':''}</span></div>{available?<a className="buy-button" href={p.buyUrl} target="_blank" rel="noopener noreferrer">Buy <ArrowUpRight size={18}/></a>:<button className="buy-button" disabled title="Buying will be available when partner listings launch">Buy <ArrowUpRight size={18}/></button>}<a href="/calculator" className="calculate-link">Compare savings with Enerlizer</a></div></article>})}</section></>;
}
