'use client';
import {useRef,useState} from 'react';
import {Fan,Sun,Wind,Snowflake,Lightbulb,ArrowUpRight,X,Check} from 'lucide-react';
import {products,money,type Product,type ProductCategory} from '@/lib/products';
const icons={Fans:Fan,Solar:Sun,Wind:Wind,Cooling:Snowflake,Lighting:Lightbulb};
export default function ProductShop(){
 const [category,setCategory]=useState('All');const [selection,setSelection]=useState<Product|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const filtered=products.filter(p=>category==='All'||p.category===category);
 function buy(product:Product){if(product.buyUrl&&!product.sample){window.open(product.buyUrl,'_blank','noopener,noreferrer');return;}setSelection(product);dialog.current?.showModal();}
 return <><div className="shop-intro"><span className="pathway-label">Enerlyze products</span><h1>Choose a better<br/>way to use energy.</h1><p>Efficient everyday appliances and renewable possibilities, connected to the savings you calculate.</p><div className="sample-notice">Demo shop. Products, prices, and partner labels are examples. Demo purchases create no order and charge no money. Real partner buying links will be added when available.</div></div><div className="shop-toolbar"><nav aria-label="Product categories">{['All','Fans','Cooling','Lighting','Solar','Wind'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</nav><span>{filtered.length} options</span></div><section className="product-grid" aria-label="Products">{filtered.map(p=>{const Icon=icons[p.category as ProductCategory];return <article id={p.id} key={p.id} className="product-card"><div className={`product-art art-${p.category.toLowerCase()}`}><Icon size={88} strokeWidth={1} aria-hidden="true"/></div><div className="product-copy"><span className="recommendation-tag">Sample partner product</span><h2>{p.name}</h2><p>{p.description}</p><span className="product-spec">{p.spec}</span><div className="product-price"><strong>{money(p.price)}</strong><span>illustrative price</span></div><button className="buy-button" onClick={()=>buy(p)}>Try demo purchase <ArrowUpRight size={18}/></button><a href="/calculator" className="calculate-link">Compare savings first</a></div></article>})}</section><dialog ref={dialog} className="purchase-dialog" onClick={event=>{if(event.target===dialog.current)dialog.current.close();}}><button aria-label="Close demo purchase" className="dialog-close" onClick={()=>dialog.current?.close()}><X/></button><Check className="purchase-check"/><h2>Demo purchase complete</h2><p>{selection?.name}</p><strong>{selection?money(selection.price):''}</strong><p>This is a sample checkout demonstration. No payment was taken and no order was sent. When approved partner links are connected, this action will take you to the seller’s checkout.</p><button className="buy-button" onClick={()=>dialog.current?.close()}>Continue exploring</button></dialog></>;
}
